@extends('layouts.app')
@section('title','Terms of use')
@section('content')
<div class="container">
<h2>Transpartner Logistics' Terms of use</h2>
<p>&nbsp;</p>
<p>1.      <u>Introduction</u>. Welcome to <a href="http://www.transpartnerlogistics.co.zw/">Transpartner Logistics</a> (the "Site"), which is owned and operated by Transpartner Logistics Pvt Ltd. ("TRANSPARTNER LOGISTICS" or "We"). We provide the Site and the information and services offered on the Site to you, whether you are a shipper or carrier, (&ldquo;You&rdquo;) subject to the following Terms of Use (the "Terms"). By using the Site, You agree to be bound by the Terms. We may, in our sole discretion, modify the Terms without notice to You. Therefore, please continue to review the Terms when using the Site. By continuing to access and use the Site after the Terms have been modified, you are agreeing to such modifications.  In addition, when using particular TRANSPARTNER LOGISTICS services or features on the Site, you shall be subject to any posted guidelines or rules applicable to such services or features that may be posted from time to time. All such guidelines or rules are hereby incorporated by reference into the Terms.  In the event of any conflict between such posted guidelines or rules and these Terms, the posted guidelines or rules shall govern.
</p>
<p><br>
2.    <u>Description of Service</u>. The Site is a proprietary freight shipping platform where: (i) carriers can advertise, post rates and lanes; (ii) shippers can view, price and submit freight transportation requests; and (iii) if they wish, shippers and carriers can enter into a contractual relationship based on an industry standard Bills of Lading and rules regarding missed pick-ups, delays and other special circumstances. The Site is for land, air and sea transportation and related services, including tracking of shipments, in Southern Africa. At all times, TRANSPARTNER LOGISTICS is acting as an agent and not as a shipper or carrier and for purposes of clarity the transport of goods by a carrier on behalf of a shipper, even when contracted through the Site, is not part of the Services (as defined). The Site and the information, features, applications and services available on the Site may be referred to herein collectively as the "Service." Unless explicitly stated otherwise, any new features or services that augment or enhance the Service in the future shall be considered part of the Service and subject to the Terms.</p>
<p>3.    <u>License.</u> Subject to the provisions and conditions of these Terms, TRANSPARTNER LOGISTICS hereby grants You a limited, non-exclusive, non-transferable, during the term hereof right and license to use the Site solely for the purposes outlined herein. No right or license is granted to You other than those stated before. You are prohibited from causing or permitting the reverse engineering, disassembly or de-compilation of the software which runs the Site.</p>
<p>4.    <u>Authorization</u><strong>:</strong> You confirm that any individual using the Site on your behalf has authority to do so and to bind You. No one under the age of 18 may use the site.</p>
<p>5.    <u>Selection and Ranking of Carriers.</u> To be eligible to be listed as a carrier on the Site carriers must meet minimal requirements which include, but are not limited to, (i) one year of uninterrupted business operations in the field with the same management; (ii) have at least five trucks in operation; trust and credibility; and (iii) pass a credit report. Carriers are ranked according to their historical level of performance on services delivered through the Site. The rankings will be based on flags associated with the Carrier&rsquo;s use of the system, including meeting commitments specified in their individual lane postings. Flags are based on: (i) cancelations; (ii) late pickups; and (iii) late deliveries.</p>
<p>6.    <u>Selection of Shippers.</u> TRANSPARTNER LOGISTICS will use its commercially reasonable efforts to verify shippers&rsquo; reputation, reliability and activities on the Site. TRANSPARTNER LOGISTICS will use its proprietary, custom algorithms to identify any shipper submitting false load quotes to access carrier data. Any such shipper will be barred from the Site.</p>
<p>7.    <u>Restrictions.</u> The Site is not open to: (i) freight brokers whether they are acting for a carrier or shipper; (ii) carriers who act as a broker; or (iii) carriers who act as double-brokers (where a carrier agrees to transport freight and subsequently re-brokers it to another carrier) unless, a Carrier refers the opportunity to a carrier with which it has a written interline agreement.<br>
  <br>
  8.    <u>Your Obligations</u><strong>. </strong>Whether You are a shipper or carrier, You agree to use the Service only for lawful purposes.  You are responsible for all content and information uploaded to, or generated through, the Service by You or on your behalf.  You shall not utilize the Service to misrepresent an affiliation with any person or organization, violate the legal rights of any third party, or to upload or transmit any defamatory, indecent, obscene, harassing or otherwise objectionable material, or any material that is protected by copyright, trademark or trade secret, without permission from the applicable owner.<br>
  <br>
  9.    <u>Fees.</u> The fees paid by shippers will be composed of the price charged by the carrier and TRANSPARTNER LOGISTICS&rsquo;s fee. Initially, TRANSPARTNER LOGISTICS will have the same transaction fees built into the price paid by the shipper. Carriers whose system rating goes below a minimum acceptable ranking may incur an increase in the transactional fee on their pricing.<br>
  <br>
  10.  <u>Site Security.</u> TRANSPARTNER LOGISTICS will use commercially reasonable security technologies (such as encryption, password protection, hacking protection and firewall protection) in providing the Service, and You shall comply with the applicable TRANSPARTNER LOGISTICS security guidelines and procedures made known to You through the Service or otherwise. However, TRANSPARTNER LOGISTICS does not control the transfer of data over telecommunications facilities, including the Internet, and TRANSPARTNER LOGISTICS does not warrant secure operation of the Service or that such security technologies will be able to prevent third party disruptions of the Service. <br>
  <br>
  11.  <u>Privacy and History</u>. Data uploaded by carriers is shared only with shippers. To protect carrier data.<br>
  <br>
  12.  <u>Information You Provide to Us.</u> From time to time You are required to provide or update certain information in order to access or take advantage of certain features offered on the Site (for example, to join our email distribution list or to request that we send You information). Any information You provide us or post on the Site shall be true, accurate, current and complete. Additionally, in order to provide the Services to You or Your clients we may acquire from You contact information for You and/or your clients. Any such information will be used solely to provide the Services to You or your clients.<br>
  <br>
  13.  <u>Limitation of Liability.</u> You recognize that TRANSPARTNER LOGISTICS is providing the Site as is. TRANSPARTNER LOGISTICS is not involved in and does not accept any responsibility for shipments or other related services procured through the Site and  shall not be responsible or liable for the accuracy, completeness, usefulness or availability of any information or other content, data, text, graphics or any other materials transmitted or made available via the Service. TRANSPARTNER LOGISTICS shall not be responsible or liable for any decisions made in reliance on such information.<br>
  <br>
  14.  <u>Limited Warranty by TRANSPARTNER LOGISTICS.</u>  TRANSPARTNER LOGISTICS warrants that the Service will perform substantially in accordance with Our operating and technical documentation relating to the features, functions and operation of the Service as established from time to time. TRANSPARTNER LOGISTICS&rsquo;s sole obligation with respect to a breach of the warranty shall be to repair or replace any component giving rise to the breach of warranty. The limited warranty in this is in lieu of all other warranties.  TRANSPARTNER LOGISTICS MAKES NO OTHER WARRANTIES WHATSOEVER, EXPRESS OR IMPLIED, WITH REGARD TO THE SERVICE, IN WHOLE OR IN PART, OR ANY OTHER MATTER UNDER THESE TERMS.  TRANSPARTNER LOGISTICS EXPLICITLY DISCLAIMS ALL WARRANTIES OF MERCHANTABILITY AND OF FITNESS FOR A PARTICULAR PURPOSE.  TRANSPARTNER LOGISTICS EXPRESSLY DOES NOT WARRANT THAT THE SERVICE, IN WHOLE OR IN PART, WILL BE ERROR FREE, WILL OPERATE WITHOUT INTERRUPTION, WILL BE COMPATIBLE WITH ANY HARDWARE OR SYSTEMS SOFTWARE CONFIGURATION.<br>
  <br>
  15.  <u>Confidentiality</u>. Except as otherwise permitted under these Terms, TRANSPARTNER LOGISTICS will not disclose to any third party carrier&rsquo;s rates and lanes.  We will use at least the same standard of care to maintain the confidentiality of carrier&rsquo;s rates and lanes as used to maintain the confidentiality of our own confidential information.<br>
  <br>
  16.  <u>Indemnification</u>. You shall defend and hold harmless TRANSPARTNER LOGISTICS against and in respect to any and all claims, demands, losses, costs, expenses, obligations, liabilities, damages, recoveries, and deficiencies, including interest, penalties and reasonable attorney fees that TRANSPARTNER LOGISTICS shall incur or suffer, that arise, result from, or relate to any breach of or failure by You to perform any of your obligations in these Terms. <br>
  <br>
  17.  <u>Limitation of Remedies and Liability.</u> Other than any outstanding amounts due to TRANSPARTNER LOGISTICS hereunder, both parties limit their liability with respect to the use and the performance of the Site or Services to an amount not to exceed the amount paid by You to TRANSPARTNER LOGISTICS in the immediately preceding 12 month period.<br>
  <br>
  18.  <u>Term.</u> These Terms and the attached right and license shall terminate in any of the following events: (i) You not paying any fees due to TRANSPARTNER LOGISTICS; (ii) failure to respect the provisions hereof or any other provisions stipulated by TRANSPARTNER LOGISTICS; (iii) discontinuance of the Site; or (iv) You issuing a written notice of termination to TRANSPARTNER LOGISTICS. Upon termination of these Terms You will discontinue further use of the Site.  Termination of these Terms will not relieve You from making payments which may be owing to TRANSPARTNER LOGISTICS or seeking any other remedies under law or in equity.<br>
  <br>
  19.  <u>Force Majeure. </u>Except with respect to the payment of fees hereunder, neither party will be liable to the other for any failure or delay in performance under these Terms solely during the period necessitated by the force majeure, due to circumstances beyond its reasonable control. Force majeure is limited to acts of war, terrorist acts, natural disasters, accident, labor disruption, acts, omissions and defaults of third parties and official, governmental and judicial action not the fault of the party failing or delaying in performance, or the threat of any of the foregoing.<br>
  <br>
  20.  <u>Assignment.</u> Client may not assign these Terms without TRANSPARTNER LOGISTICS&rsquo; consent. TRANSPARTNER LOGISTICS may assign these Terms and its rights and obligations hereunder at will.<br>
  <br>
  21.<u>Customer Service</u> is part of TRANSPARTNER LOGISTICS transactional fees which gives you the rights to customer service<br>
  <br>
  22.  <u>Governing Law.</u>  These Terms and performance under these Terms shall be governed by: (i) the laws of the Republic of Zimbabwe without giving effect to its conflict of laws provisions with jurisdiction and venue in the courts of competent jurisdiction for the district of Republic of Zimbabwe or (ii) for carriers whose head office and primary service region originates in another Southern African Country then these Terms shall be governed by the laws of the Republic of Zimbabwe without giving effect to its conflict of laws provisions with jurisdiction and venue in the Republic of Zimbabwe.</p>
</div>

@stop